[package]
name = "date-timestamp"
version = "0.1.0"
edition = "2021"
description = "Prints the UNIX timestamp of today's midnight"

[dependencies]
clap = { version = "4.2.3", features = ["derive"] }
time = { version = "0.3.20", features = ["local-offset", "formatting"] }
